apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos-post-deployment
  labels:
    app: prod-post-pablo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-post-pablo
  template:
    metadata:
      labels:
        app: prod-post-pablo
    spec:
      containers:
      - name: prod-post-pablo
        image: palandeta/prod-post-pablo-abr26:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017"
        - name: MONGO_DB
          value: "productosdb"
        - name: MONGO_COLLECTION
          value: "products"
        resources:
          limits: 
            cpu: "300m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthpost
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthpost
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 20 