apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: prod-service
        image: palandeta/prodpabloabr26
        ports: 
        - containerPort: 5001